# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_rename_ticket_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='playbook',
            field=models.TextField(blank=True, default='', help_text='Staff response steps/playbook'),
        ),
    ]
