# Generated by Django 6.1.1 on 2026-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_rename_ticket_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='playbook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
