# Generated by Django 6.1.1 on 2026-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_drop_last_check_and_dashboard_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionconfig',
            name='start_message',
            field=models.TextField(blank=True, help_text="Posted to every active team's chat channel when the competition starts, e.g. default VM credentials"),
        ),
    ]
