# Generated by Django 6.1.1 on 2026-10-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0038_drop_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='inject_modifier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='orange_modifier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='service_modifier',
        ),
    ]
