# Generated by Django 6.1.1 on 2026-10-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0039_remove_scoringtemplate_inject_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='sla_violations',
            field=models.IntegerField(default=0, help_text='Number of SLA violations'),
        ),
    ]
