# Generated by Django 6.1.1 on 2026-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange_team', '0005_rename_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangecheck',
            name='max_points',
            field=models.PositiveIntegerField(default=0, help_text='Max score when the check has no criteria'),
        ),
        migrations.AddField(
            model_name='orangecheck',
            name='time_limit',
            field=models.DurationField(blank=True, help_text='How long the window stays open from scheduled_at', null=True),
        ),
    ]
