# Generated by Django 6.1.1 on 2026-10-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orange_team', '0006_orangecheck_max_points_orangecheck_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orangecheck',
            name='status',
        ),
    ]
